[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
db_name = test_approval
db_maxconn = 64
list_db = False
admin_passwd = $pbkdf2-sha512$600000$JARAKMU455wzxvg/x5jTOg$Sy7yzq5Jj7PojYCL4.R1LW1NhMLsS3qx4VnH2d02blyIlFVnz12IWSAiQgPnSk4o1oteWl.7nQJF7TgM6giGFA
workers = 0
max_cron_threads = 1
limit_time_real = 600
limit_time_cpu = 600
proxy_mode = True
unaccent = True
logfile = /var/log/odoo/odoo-server.log
